# Wi-Fi settings
CIRCUITPY_WIFI_SSID = "Nombre_de_la_red"
CIRCUITPY_WIFI_PASSWORD = "contrase単a_de_la_red"

# Password for web interface
CIRCUITPY_WEB_PASSWORD = "mi_contrase単a_segura"

#A la hora de ingresar la Ip en el navegador de pedira la contrase単a ingresada para acceder al Esp32, se debe dejar el Usuario en blanco, solo se ingresa la contrase単a puesta en el paso anterior.